FROM node:20-alpine

ARG IMAGE_VERSION
LABEL version=$IMAGE_VERSION

ENV NODE_ENV=production
ENV PORT=3000

WORKDIR /app

# optymalizacja warstw
COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY . .

USER node

EXPOSE 3000

CMD ["node", "server.js"]
